/* eslint-disable no-use-before-define */

import React from 'react';
import { FormattedMessage } from 'react-intl';
import video1 from '../../images/exampleSquare.jpg';
// import video2 from 'file-loader!../../assets/Abdullah_Haddad_Full_Interview.mov';

import messages from './messages';
import Header from './Header';
import Link from './Link';
import Search from './Input';
import Background from './background';
import Tile from './Tile';
import TileRow from './TileRow';
import CircleProfile from './CircleProfile';
import Modal from './Modal';
import LinkContainer from './LinkContainer';
// import ProfileImage from './ProfileImage';

import angelAjemian from '../../images/Angel_Ajemian.jpg';
import sosiOhan from '../../images/Sosi_Ohan.jpg';
import salpiProudian from '../../images/Salpi_Proudian.jpg';
import jirairHalvajian from '../../images/Jirair_Halvajian.jpg';
import sonaGildalian from '../../images/Sona_Gildalian.jpg';
import abdullahHaddad from '../../images/Abdullah_George_Haddad.jpg';
import lindaArakel from '../../images/Linda_Arakel.jpg';
import hagopAtikian from '../../images/Hagop_Atikian.jpg';
import takouhiBedros from '../../images/Takouhi_Bedros.jpg';
import vickyMasrie from '../../images/Vicky_Masrie.jpg';
import maydaHindoyan from '../../images/Mayda_Hindoyan.jpg';
import lusinMkhlmeljian from '../../images/Lusin_Mkhlmeljian.jpg';
import vahramDerOhanian from '../../images/Vahram_DerOhanian.jpg';
import dzovagSoghomonian from '../../images/Dzovag_Soghomonian.jpg';
import krikorStepanian from '../../images/Krikor_Stepanian.jpg';
import sevanTorosian from '../../images/Sevan_Torosian.jpg';
import torosToranian from '../../images/Toros_Toranian.jpg';
import vartanoushShitilian from '../../images/Vartanoush_Shitilian.jpg';
import aniAvakian from '../../images/Ani_Avakian.jpg';
import ritaSarkisian from '../../images/Rita_Sarkisian.jpg';
import haroutGhalbornian from '../../images/Harout_Ghalbornian.jpg';
import zohrabDerderian from '../../images/Zohrab_Derderian.jpg';
import janetManoushian from '../../images/Janet_Manoushian.jpg';
import zarouhiHamalian from '../../images/Zarouhi_Vanesian_Hamalian.jpg';
import sarkisBolsaghi from '../../images/Sarkis_Bolsaghi.jpg';
import taleenBekerian from '../../images/Taleen_Bekerian.jpg';
import antranikMardikian from '../../images/Antranik_Mardikian.jpg';
import georgeGildalian from '../../images/George_Gildalian.jpg';
import bedigTatouvian from '../../images/Bedig_Tavoutian.jpg';
import krikorSahagian from '../../images/Krikor_Sahagian.jpg';
import hagopKereshian from '../../images/Hagop_Kereshian.jpg';
import vaheDerderian from '../../images/Vahe_Derderian.jpg';
import mariaBekerian from '../../images/Maria_Bekerian.jpg';
import danyaDashyan from '../../images/Danya_Dashyan.jpg';
import vikenKarajian from '../../images/Viken_Karajian.jpg';
import naregDekermenjian from '../../images/Nareg_Dekermenjian.jpg';
import taleen from '../../images/Taleen.jpg';
import levonShant from '../../images/Levon_Shant.jpg';
import sarkisBalkhian from '../../images/Sarkis_Balkhian.jpg';
import hagopKazanjian from '../../images/Hagop_Kazanjian.jpg';
import hagopKazanjian2 from '../../images/Hagop_Kazanjian_2.jpg';
import maydaChavoushian from '../../images/Mayda_Chavoushian.jpg';
import shantCharoian from '../../images/Shant_Charoian.jpg';
import shushanikNarkozian from '../../images/Shushanik_Narkozian.jpg';
import kevorkBeyazbegian from '../../images/Kevork_Beyazbegian.jpg';
import garpisArabatlian from '../../images/Garpis_Arabatlian.jpg';
import shaghigMinassian from '../../images/Shaghig_Minassian.jpg';
import terezBarsoum from '../../images/Terez_Barsoum.jpg';
import hagopGeorge from '../../images/Hagop_George.jpg';
import hovhannesKeshishian from '../../images/Hovhannes_Keshishian.jpg';
import sako from '../../images/Sako.jpg';
import haroutGhazarian from '../../images/Harout_Ghazarian.jpg';
import dikranChalian from '../../images/Dikran_Chalian.jpg';
import kevorkSookiasian from '../../images/Kevork_Sookiasian.jpg';
import dzovigGhazarian from '../../images/Dzovig_Ghazarian.jpg';
import hovsepMadarjian from '../../images/Hovsep_Madarjian.jpg';
import sevanMadarjian from '../../images/Sevan_Madarjian.jpg';
import narineMadarjian from '../../images/Narine_Madarjian.jpg';
import lusinMadarjian from '../../images/Lusin_Madarjian.jpg';
import nazaretMelkonian from '../../images/Nazaret_Melkonian.jpg';
import garenBalkhian from '../../images/Garen_Balkhian.jpg';
import kevorkMouradian from '../../images/Kevork_Mouradian.jpg';
import hayasaTahmazyan from '../../images/Hayasa_Tahmazyan.jpg';
import natelaStepanian from '../../images/Natela_Stepanian.jpg';
import anitaBoghoyan from '../../images/Anita_Boghoyan.jpg';
import sophiNersisyan from '../../images/Sophi_Nersisyan.jpg';
import sakoSarkisian from '../../images/Sako_Sarkisian.jpg';
import hovsepKazanjian from '../../images/Hovsep_Kazanjian.jpg';
import dikranuhiJrazian from '../../images/Dikranuhi_Jrazian.jpg';
import arshoughKakoyian from '../../images/Arshough_Kakoyian.jpg';

import rerooted from '../../images/rerooted.png';

export default class Refugees extends React.PureComponent {
  constructor(props) {
    super(props);
    this.state = {
      selectedPerson: null,
      selectedPeople: null,
      people: [
        {
          name: 'Angel Ajemian',
          armenianName: 'Անճէլ Աճէմեան',
          arabicName: '',
          cityOfResidence: 'Yerevan, Armenia',
          armenianCityOfResidence: 'Երեւան, Հայաստան',
          arabicCityOfResidence: 'يريفان، أرمينيا',
          age: 37,
          armenianAge: 37,
          arabicAge: 37,
          birthplace: 'Kuwait',
          armenianBirthplace: 'Քուվեյթ',
          arabicBirthplace: 'الكويت',
          ancestralCity: 'Sassoun',
          armenianAncestralCity: 'Սասուն',
          arabicAncestralCity: 'ساسون',
          route: 'Bus to Beirut, Airplane to Yerevan',
          armenianRoute: 'Ավտոպուս դէպի Պէյրութ, Օդանաւ դէպի Երեւան',
          arabicRoute: 'أتوبيس إلی بيروت وطائرة إلی يريفان ',
          quote:
            'A lawyer called me and told me he had been kidnapped by ISIS alongside my husband, Minas. I did not believe him. I thought he was lying because everyone knew my husband was kidnapped and maybe this man just wanted to upset me.  But then he said, “You have three candles.” Minas used to say that our three kids were candles that lit up our life. When the man said that I knew that he had been with Minas.',
          shortVideoLink: '',
          fullVideoLink: 'https://www.youtube.com/embed/k-YK154hxO0',
          img: angelAjemian,
        },
        {
          name: 'Salpi Proudian',
          armenianName: 'Սալբի Բրուտեան',
          arabicName: '',
          cityOfResidence: 'Yerevan, Armenia',
          armenianCityOfResidence: 'Երեւան, Հայաստան',
          arabicCityOfResidence: 'يريفان، أرمينيا',
          age: 55,
          armenianAge: 55,
          arabicAge: 55,
          birthplace: 'Aleppo, Syria',
          armenianBirthplace: 'Հալէպ, Սուրիա',
          arabicBirthplace: 'حلب، سوريا',
          ancestralCity: 'Ainteb',
          armenianAncestralCity: 'Այնթապ',
          arabicAncestralCity: 'عنتاب',
          route: 'Airplane to Yerevan, Armenia',
          armenianRoute: 'Օդանաւ դէպի Երեւան',
          arabicRoute: 'طائرة إلی يريفان',
          quote:
            "Of course, I would like to be in a situation where I don't have to worry about tomorrow. The most pressing thing is the house rent. You go to bed every night and you wake up every morning with that thought on your mind, thinking how am I going to pay the rent this month so I have a place to stay.",
          shortVideoLink: '',
          fullVideoLink: 'https://www.youtube.com/embed/LxfUNmWY-Ts',
          img: salpiProudian,
          video: video1,
        },
        {
          name: 'Jirair Halvajian',
          armenianName: 'Ճիրայր Հալվաճեան',
          arabicName: '',
          cityOfResidence: 'Yerevan, Armenia',
          armenianCityOfResidence: 'Երեւան, Հայաստան',
          arabicCityOfResidence: 'يريفان، أرمينيا',
          age: 56,
          armenianAge: 56,
          arabicAge: 56,
          birthplace: 'Aleppo, Syria',
          armenianBirthplace: 'Հալէպ, Սուրիա',
          arabicBirthplace: 'حلب، سوريا',
          ancestralCity: 'Marash',
          armenianAncestralCity: 'Մարաշ',
          arabicAncestralCity: 'مرعش',
          route: 'Airplane to Yerevan, Armenia',
          armenianRoute: 'Օդանաւ դէպի Երեւան',
          arabicRoute: 'طائرة إلی يريفان',
          quote:
            "I'd like to go back to Aleppo, I've missed Aleppo very much--the environment, my friends. I really miss it. If Aleppo were the Aleppo it used to be, I wouldn't stay in Armenia for a minute. I'd take my children and leave.",
          shortVideoLink: '',
          fullVideoLink: 'https://www.youtube.com/embed/qPsMpTGplUE',
          img: jirairHalvajian,
          video: video1,
        },
        {
          name: 'Sona Gildalian',
          armenianName: 'Սոնա Կիլտալեան',
          arabicName: '',
          cityOfResidence: 'Yerevan, Armenia',
          armenianCityOfResidence: 'Երեւան, Հայաստան',
          arabicCityOfResidence: 'يريفان، أرمينيا',
          age: 62,
          armenianAge: 62,
          arabicAge: 62,
          birthplace: 'Aleppo, Syria',
          armenianBirthplace: 'Հալէպ, Սուրիա',
          arabicBirthplace: 'حلب، سوريا',
          ancestralCity: 'Ainteb',
          armenianAncestralCity: 'Այնթապ',
          arabicAncestralCity: 'عنتاب',
          route: 'Bus to Beirut, Airplane to Yerevan',
          armenianRoute: 'Ավտոպուս դէպի Պէյրութ, Օդանաւ դէպի Երեւան',
          arabicRoute: 'طائرة إلی يريفان',
          quote:
            "We had relatives who visited us in Aleppo from Armenia. When I'd tell them I wanted to go to Armenia to see what it is like, they would say, “Yes, come and see your motherland, but you have already built one in Aleppo.” There is already a motherland built in Aleppo. We have our churches, theatres, a prelacy. Everything. ",
          shortVideoLink: '',
          fullVideoLink: 'https://www.youtube.com/embed/pM6_m6EA-E4',
          img: sonaGildalian,
          video: video1,
        },
        {
          name: 'Abdullah George Haddad',
          armenianName: 'Ապտըլլայ Ճորճ Հատատ',
          arabicName: 'عبد الله جورج حداد',
          cityOfResidence: 'Yerevan, Armenia',
          armenianCityOfResidence: 'Երեւան, Հայաստան',
          arabicCityOfResidence: 'يريفان، أرمينيا',
          age: 53,
          armenianAge: 53,
          arabicAge: 53,
          birthplace: 'Aleppo, Syria',
          armenianBirthplace: 'Հալէպ, Սուրիա',
          arabicBirthplace: 'حلب، سوريا',
          ancestralCity: 'Ainteb',
          armenianAncestralCity: 'Այնթապ',
          arabicAncestralCity: 'عنتاب',
          route: 'Bus through Turkey and Georgia to Armenia',
          armenianRoute:
            'Ավտոպուս դէպի Հայաստան Թուրքական եւ Վրացական ճամբայով',
          arabicRoute: 'أتوبيس إلی يريفان بطريق تركيا وجورجيا',
          quote:
            'But my one desire is to get a place where I can work with my older two sons and take them under my wing. Not necessarily a business. Just a place where my sons can move their bodies and use their mind. Like therapy for them. Business is not my thing.',
          shortVideoLink: '',
          fullVideoLink: 'https://www.youtube.com/embed/N016Ka053tQ',
          img: abdullahHaddad,
          video: video1,
        },
        {
          name: 'Maria Bekerian',
          armenianName: 'Մարիա Պէքէրեան',
          arabicName: '',
          cityOfResidence: 'Yerevan, Armenia',
          armenianCityOfResidence: 'Երեւան, Հայաստան',
          arabicCityOfResidence: 'يريفان، أرمينيا',
          age: 29,
          armenianAge: 29,
          arabicAge: 29,
          birthplace: 'Aleppo, Syria',
          armenianBirthplace: 'Հալէպ, Սուրիա',
          arabicBirthplace: 'حلب، سوريا',
          ancestralCity: '',
          armenianAncestralCity: '',
          arabicAncestralCity: '',
          route: '',
          armenianRoute: '',
          arabicRoute: '',
          quote:
            'We were under attack. Rockets hit all the four sides of my house. God kept my house from being hit. I was pregnant at the time, and that is why we decided we needed to leave. My family was already in Armenia and we made the decision to join them.',
          shortVideoLink: '',
          fullVideoLink: '',
          img: mariaBekerian,
          video: video1,
        },
        {
          name: 'Vahe Derderian',
          armenianName: 'Վահե Տերտերեան',
          arabicName: 'ڤاهة ديرديريان',
          cityOfResidence: 'Gyumri, Armenia',
          armenianCityOfResidence: 'Գյումրի, Հայաստան',
          arabicCityOfResidence: 'غيومري، أرمينيا',
          age: 51,
          armenianAge: 51,
          arabicAge: 51,
          birthplace: 'Aleppo, Syria',
          armenianBirthplace: 'Հալէպ, Սուրիա',
          arabicBirthplace: 'حلب، سوريا',
          ancestralCity: '',
          armenianAncestralCity: '',
          arabicAncestralCity: '',
          route: '',
          armenianRoute: '',
          arabicRoute: '',
          quote:
            "We didn't learn Armenian history in school buecase it wasn't allowed back in my days...We learned how to read and write in Armenian and about our religion. But there was a lot of censorship when it came to Armenian history. We weren't allowed to learn it....There was an established curriculum and that was it. We had an Arab principal in every Armenian school. So we had two principals, an Armenian and an Arab....After 1973, Armenians started to enjoy more freedom , but for example, Kurds still didn't have a right to their language or any classes in school.",
          shortVideoLink: '',
          fullVideoLink: '',
          img: vaheDerderian,
          video: video1,
        },
        {
          name: 'Sosi Ohan',
          armenianName: 'Սոսի Օհան',
          arabicName: '',
          cityOfResidence: 'Yerevan, Armenia',
          armenianCityOfResidence: 'Երեւան, Հայաստան',
          arabicCityOfResidence: 'يريفان، أرمينيا',
          age: 57,
          armenianAge: 57,
          arabicAge: 57,
          birthplace: 'Qamishli, Syria',
          armenianBirthplace: 'Քամիշլի, Սուրիա',
          arabicBirthplace: ' القامشلي‎، سوريا',
          ancestralCity: 'Sassoun',
          armenianAncestralCity: 'Սասուն',
          arabicAncestralCity: 'ساسون',
          route: 'Airplane to Damascus, Beirut, then Yerevan',
          armenianRoute: 'Օդանաւ դէպի Դամասկոս, Պէյրութ ի վերջ Երեւան',
          arabicRoute: 'طائرة إلی دمشق ثم بيروت ثم يريفان',
          quote:
            'My grandparents who survived the genocide would say, “If only we had some Armenian soil, we would want to put it on our graves.” That stays in my head until now. If I buy a vegetable or something here in Armenia and there is some soil in the bag, I cannot throw it in the trash.  I throw it outside and let the soil go out. I cannot put it in the trash. ',
          shortVideoLink: '',
          fullVideoLink: 'https://www.youtube.com/embed/-SOp0lCwR2c',
          img: sosiOhan,
          video: video1,
        },
        {
          name: 'Hagop Kereshian',
          armenianName: 'Յաքոբ Քէրէշեան',
          arabicName: '',
          cityOfResidence: 'Yerevan, Armenia',
          armenianCityOfResidence: 'Երեւան, Հայաստան',
          arabicCityOfResidence: 'يريفان، أرمينيا',
          age: 75,
          armenianAge: 75,
          arabicAge: 75,
          birthplace: 'Aleppo, Syria',
          armenianBirthplace: 'Հալէպ, Սուրիա',
          arabicBirthplace: 'حلب، سوريا',
          ancestralCity: '',
          armenianAncestralCity: '',
          arabicAncestralCity: '',
          route: '',
          armenianRoute: '',
          arabicRoute: '',
          quote:
            'There were lots of difficulties for my parents. They left their homes and everything and … they got to Aleppo, with nothing there for them. There was nothing.  They even had to live in places next to animals. They lived in tiny room like this with two or three families. After that they started building houses out of wood. Then they started building houses out of stone. My father built his house in 1935 or 1936 with his own hands. They had one room built and he saw how it was done and then after work he would come and build the other rooms with my mother.',
          shortVideoLink: '',
          fullVideoLink: '',
          img: hagopKereshian,
          video: video1,
        },
        {
          name: 'Krikor Sahagian',
          armenianName: 'Գրիքոր Սահակեան',
          arabicName: '',
          cityOfResidence: 'Yerevan, Armenia',
          armenianCityOfResidence: 'Երեւան, Հայաստան',
          arabicCityOfResidence: 'يريفان، أرمينيا',
          age: 64,
          armenianAge: 64,
          arabicAge: 64,
          birthplace: 'Aleppo, Syria',
          armenianBirthplace: 'Հալէպ, Սուրիա',
          arabicBirthplace: 'حلب، سوريا',
          ancestralCity: '',
          armenianAncestralCity: '',
          arabicAncestralCity: '',
          route: '',
          armenianRoute: '',
          arabicRoute: '',
          quote:
            'The Armenian community in Syria is proud of the Arab people. We feel proud that the Arab people took us in. When we ran away from the Turks, Arabs ooked after us. And for 90, 95 years we lived peacefully with Arab people. We were proud to live together.',
          shortVideoLink: '',
          fullVideoLink: '',
          img: krikorSahagian,
          video: video1,
        },
        {
          name: 'Viken Karajian',
          armenianName: 'Վիքէն Գարաճեան   ',
          arabicName: '',
          cityOfResidence: 'Yerevan, Armenia',
          armenianCityOfResidence: 'Երեւան, Հայաստան',
          arabicCityOfResidence: 'يريفان، أرمينيا',
          age: 34,
          armenianAge: 34,
          arabicAge: 34,
          birthplace: 'Aleppo, Syria',
          armenianBirthplace: 'Հալէպ, Սուրիա',
          arabicBirthplace: 'حلب، سوريا',
          ancestralCity: '',
          armenianAncestralCity: '',
          arabicAncestralCity: '',
          route: '',
          armenianRoute: '',
          arabicRoute: '',
          quote:
            "Yes, the Armenia we dreamed about is not this. The locals tell us, 'It is what it is.' And at the end we have no right to criticize it because we are staying here. It's a blessing we have Armenia. We cannot say anything else. That's the truth...No matter what other Syrian-Armenians might say about Armenia, I say it's a blessing that there is Armenia.",
          shortVideoLink: '',
          fullVideoLink: '',
          img: vikenKarajian,
          video: video1,
        },
        {
          name: 'Bedig Tavoutian',
          armenianName: 'Պետիկ Դավուդյան',
          arabicName: '',
          cityOfResidence: 'Gyumri, Armenia',
          armenianCityOfResidence: 'Գյումրի, Հայաստան',
          arabicCityOfResidence: 'غيومري، أرمينيا',
          age: 29,
          armenianAge: 29,
          arabicAge: 29,
          birthplace: 'Aleppo, Syria',
          armenianBirthplace: 'Հալէպ, Սուրիա',
          arabicBirthplace: 'حلب، سوريا',
          ancestralCity: '',
          armenianAncestralCity: '',
          arabicAncestralCity: '',
          route: '',
          armenianRoute: '',
          arabicRoute: '',
          quote:
            "It is true that the last years of my life, the years I spent in Armenia are the most difficult days of my life, but they are also the first years I've tried to live on my own, gaining life experience far away from my parents--my family. My first and last dream is to establish my personal business, to have my own place, and my own family in Armenia.",
          shortVideoLink: '',
          fullVideoLink: '',
          img: bedigTatouvian,
          video: video1,
        },
        {
          name: 'Dzovinar Yeretsian',
          armenianName: 'Ծովինար Երէցեան',
          arabicName: '',
          cityOfResidence: 'Yerevan, Armenia',
          armenianCityOfResidence: 'Երեւան, Հայաստան',
          arabicCityOfResidence: 'يريفان، أرمينيا',
          age: 59,
          armenianAge: 59,
          arabicAge: 59,
          birthplace: 'Qamishli, Syria',
          armenianBirthplace: 'Քամիշլի, Սուրիա',
          arabicBirthplace: ' القامشلي‎، سوريا',
          ancestralCity: '',
          armenianAncestralCity: '',
          arabicAncestralCity: '',
          route: '',
          armenianRoute: '',
          arabicRoute: '',
          quote:
            "In my grandfather’s life he never laughed. He never had a smile. We would say, “Dede, why don’t you laugh?” He said, “How could I laugh? When I was seven years old, I lost my seven siblings and saw my mother leave my baby brother behind in the desert.I will never be able to not see that.” He never laughed....It is very good to tell these stories so that we as Armenians do not forget or lose them. Our generation and our kids' and their kids’ generations should know that Armenians still exist. Yes, we are few, but we are Armenian, and we will not forget it.",
          shortVideoLink: '',
          fullVideoLink: '',
          img: rerooted,
          video: video1,
        },
        {
          name: 'George Gildalian',
          armenianName: 'Ճորճ Կիլտալեան',
          arabicName: '',
          cityOfResidence: 'Yerevan, Armenia',
          armenianCityOfResidence: 'Երեւան, Հայաստան',
          arabicCityOfResidence: 'يريفان، أرمينيا',
          age: 52,
          armenianAge: 52,
          arabicAge: 52,
          birthplace: 'Aleppo, Syria',
          armenianBirthplace: 'Հալէպ, Սուրիա',
          arabicBirthplace: 'حلب، سوريا',
          ancestralCity: '',
          armenianAncestralCity: '',
          arabicAncestralCity: '',
          route: '',
          armenianRoute: '',
          arabicRoute: '',
          quote:
            'I would never imagine that a Muslim, a Kurd, or a Yezidi from Syria would treat me as bad as certain Armenians have treated me here in Armenia. ',
          shortVideoLink: '',
          fullVideoLink: '',
          img: georgeGildalian,
          video: video1,
        },
        {
          name: 'Antranik Mardikian',
          armenianName: 'Անդրանիկ Մարտիկեան',
          arabicName: 'انطرانيك مارديكيان',
          cityOfResidence: 'Yerevan, Armenia',
          armenianCityOfResidence: 'Երեւան, Հայաստան',
          arabicCityOfResidence: 'يريفان، أرمينيا',
          age: 76,
          armenianAge: 76,
          arabicAge: 76,
          birthplace: 'Aleppo, Syria',
          armenianBirthplace: 'Հալէպ, Սուրիա',
          arabicBirthplace: 'حلب، سوريا',
          ancestralCity: '',
          armenianAncestralCity: '',
          arabicAncestralCity: '',
          route: '',
          armenianRoute: '',
          arabicRoute: '',
          quote:
            'I never though I would leave Damascus. And I did not even leave because of the war. I came here at first to see my son. We came for New Year’s and planned to stay for 20 days...Then, the plans stopped running and the ticket was cancelled...We had to stay.  Nothing remained. There were no planes. There was no reason to go back. ',
          shortVideoLink: '',
          fullVideoLink: '',
          img: antranikMardikian,
          video: video1,
        },
        {
          name: 'Taleen Bekerian',
          armenianName: 'Թալին Պեքէրեան',
          arabicName: '',
          cityOfResidence: 'Yerevan, Armenia',
          armenianCityOfResidence: 'Երեւան, Հայաստան',
          arabicCityOfResidence: 'يريفان، أرمينيا',
          age: 21,
          armenianAge: 21,
          arabicAge: 21,
          birthplace: 'Aleppo, Syria',
          armenianBirthplace: 'Հալէպ, Սուրիա',
          arabicBirthplace: 'حلب، سوريا',
          ancestralCity: '',
          armenianAncestralCity: '',
          arabicAncestralCity: '',
          route: '',
          armenianRoute: '',
          arabicRoute: '',
          quote:
            'I had hoped to go to University, and that was my goal because I was the first one of my family that would study for that long. My brother worked. My sister worked....I wanted to succeed, graduate from Univesrity, and find a good job. But I was not lucky, and we had to leave to Armenia. I got my high school diploma here, but I still have not started University. I had to start working because the economic situation here is difficult.',
          shortVideoLink: '',
          fullVideoLink: '',
          img: taleenBekerian,
          video: video1,
        },
        {
          name: 'Wartina Nazarian',
          armenianName: 'Վարդինէ Նազարեան',
          arabicName: '',
          cityOfResidence: 'Yerevan, Armenia',
          armenianCityOfResidence: 'Երեւան, Հայաստան',
          arabicCityOfResidence: 'يريفان، أرمينيا',
          age: 34,
          armenianAge: 34,
          arabicAge: 34,
          birthplace: 'Abu Dhabi',
          armenianBirthplace: 'Ապու Տապի',
          arabicBirthplace: ' أبو ظبي‎',
          ancestralCity: '',
          armenianAncestralCity: '',
          arabicAncestralCity: '',
          route: '',
          armenianRoute: '',
          arabicRoute: '',
          quote:
            'We speak Armenian to our daughters, not Arabic. But we try to teach them both. We teach them both Arabic and Armenian. Let them learn both languages, even if they do not need to use it.',
          shortVideoLink: '',
          fullVideoLink: '',
          img: sarkisBolsaghi,
          video: video1,
        },
        {
          name: 'Sarkis Bolsaghi',
          armenianName: 'Սարգիս Գէւորգ Բոլսաճի',
          arabicName: '',
          cityOfResidence: 'Yerevan, Armenia',
          armenianCityOfResidence: 'Երեւան, Հայաստան',
          arabicCityOfResidence: 'يريفان، أرمينيا',
          age: 46,
          armenianAge: 46,
          arabicAge: 46,
          birthplace: 'Aleppo, Syria',
          armenianBirthplace: 'Հալէպ, Սուրիա',
          arabicBirthplace: 'حلب، سوريا',
          ancestralCity: '',
          armenianAncestralCity: '',
          arabicAncestralCity: '',
          route: '',
          armenianRoute: '',
          arabicRoute: '',
          quote:
            'I came to Armenia by the roads through Turkey and Iran. A soldier stopped me in Turkey, I asked him where the border of Nordus to Iran was, he gave me directions and asked where I came from, I said I was Armenian, he said are you? I said yes, and he asked me to turn off the car to talk for 5 minutes. I asked why he wanted me to turn off the car, and that he could just say whatever he wanted to. He said can you see these mountains, we need to make a deal. I asked what the deal was and he said this was the cemetery of Armenians. I said, God bless their souls, but he was trying to dig up gold from their graves.',
          shortVideoLink: '',
          fullVideoLink: '',
          img: sarkisBolsaghi,
          video: video1,
        },
        {
          name: 'Zarouhi Vanesian Hamalian',
          armenianName: 'Զարուհի Վանէսեան Համալեան',
          arabicName: '',
          cityOfResidence: 'Yerevan, Armenia',
          armenianCityOfResidence: 'Երեւան, Հայաստան',
          arabicCityOfResidence: 'يريفان، أرمينيا',
          age: 54,
          armenianAge: 54,
          arabicAge: 54,
          birthplace: 'Aleppo, Syria',
          armenianBirthplace: 'Հալէպ, Սուրիա',
          arabicBirthplace: 'حلب، سوريا',
          ancestralCity: '',
          armenianAncestralCity: '',
          arabicAncestralCity: '',
          route: '',
          armenianRoute: '',
          arabicRoute: '',
          quote:
            'I am doing ok and again I am a volunteer here at Zoravor Asdvazazin Church on Pushkin Street in Yerevan. I am a chairlady there. We started 3 years ago, after we came to Armenia. We went to church and spoke to the priest, Father Krikor...He asked, “How are you, Where are you from?” We said we are from Aleppo and he said if you like I can give you an hour on Friday to gather the Syrian Armenians here. We have remained so happy with Father Krikor….So we planned with some friends who became volunteers and I am the chairlady. When we started we were 14 or 15 people and now every Friday 300 women come every Friday. We do our prayers and then we have a hall and there we drink coffee as hospitality. It is a huge happiness for me to say how many people I have brought together. Thank God.',
          shortVideoLink: '',
          fullVideoLink: '',
          img: zarouhiHamalian,
          video: video1,
        },
        {
          name: 'Janet Manoushian',
          armenianName: 'Ճանէթ Մանուշեան',
          arabicName: '',
          cityOfResidence: 'Yerevan, Armenia',
          armenianCityOfResidence: 'Երեւան, Հայաստան',
          arabicCityOfResidence: 'يريفان، أرمينيا',
          age: 61,
          armenianAge: 61,
          arabicAge: 61,
          birthplace: 'Aleppo, Syria',
          armenianBirthplace: 'Հալէպ, Սուրիա',
          arabicBirthplace: 'حلب، سوريا',
          ancestralCity: '',
          armenianAncestralCity: '',
          arabicAncestralCity: '',
          route: '',
          armenianRoute: '',
          arabicRoute: '',
          quote:
            'I am a very hardworking woman. I am have sacrificed a lot, as far as I know and my husband knows. I got married when I was 15 and I had four children....We always welcomed guests. My husband knows. I am very hardworking. I do all the work around the house. No one else. Washing the dishes, buying food, making meals. I was hardworking....Whatever someone needs I try to do anything I can for them',
          shortVideoLink: '',
          fullVideoLink: '',
          img: janetManoushian,
          video: video1,
        },
        {
          name: 'Zohrab Derderian',
          armenianName: 'Զոհրապ Տէրտէրեան ',
          arabicName: '',
          cityOfResidence: 'Yerevan, Armenia',
          armenianCityOfResidence: 'Երեւան, Հայաստան',
          arabicCityOfResidence: 'يريفان، أرمينيا',
          age: 61,
          armenianAge: 61,
          arabicAge: 61,
          birthplace: 'Kobani, Syria',
          armenianBirthplace: 'Արաբունար, Սուրիա',
          arabicBirthplace: 'عين العرب، سوريا',
          ancestralCity: '',
          armenianAncestralCity: '',
          arabicAncestralCity: '',
          route: '',
          armenianRoute: '',
          arabicRoute: '',
          quote:
            "For work I would personally interacted with Kurds a lot. I had a car, a mini-bus, that I would drive between Aleppo and Kobani. The most of the people were Kurds there were very few Armenians left in Kobani. Yes, sometimes when I would go to my mother's house in Aleppo and was speaking Armenian I would mix in a Kurdish word. Just liked Armenians here mix in Russian words, we did the same thing. Arapunar is on the Turkish border. Between our country and theirs there is only rope. You can see the soldiers facing each other on each side.",
          shortVideoLink: '',
          fullVideoLink: '',
          img: zohrabDerderian,
          video: video1,
        },
        {
          name: 'Harout Ghalbornian',
          armenianName: 'Հարութ Խալպորնեան',
          arabicName: '',
          cityOfResidence: 'Yerevan, Armenia',
          armenianCityOfResidence: 'Երեւան, Հայաստան',
          arabicCityOfResidence: 'يريفان، أرمينيا',
          age: 36,
          armenianAge: 36,
          arabicAge: 36,
          birthplace: 'Aleppo, Syria',
          armenianBirthplace: 'Հալէպ, Սուրիա',
          arabicBirthplace: 'حلب، سوريا',
          ancestralCity: '',
          armenianAncestralCity: '',
          arabicAncestralCity: '',
          route: '',
          armenianRoute: '',
          arabicRoute: '',
          quote:
            "Every year we would commemorate the Genocide in our clubs. I was a member of Homenetmen. To commemorate, every year we go to Der Zor...We'd go, explain to them the history, show them the bones, take them to the churches, tell them the stories at a to a special place..We'd always remind them of what had happened. Many would be very touched. Some would look, cry and after they'd heard the story. They would listen very carefully....But we no longer do so, because the country is at war. The memorial at Der Zor is destroyed. They took out all that was possible to save, but the rest has been destroyed.",
          shortVideoLink: '',
          fullVideoLink: '',
          img: haroutGhalbornian,
          video: video1,
        },
        {
          name: 'Rita Sarkisian',
          armenianName: 'Ռիդա Սարքիսեան',
          arabicName: '',
          cityOfResidence: 'Yerevan, Armenia',
          armenianCityOfResidence: 'Երեւան, Հայաստան',
          arabicCityOfResidence: 'يريفان، أرمينيا',
          age: 54,
          armenianAge: 54,
          arabicAge: 54,
          birthplace: 'Kuwait',
          armenianBirthplace: 'Քուվեյթ',
          arabicBirthplace: 'الكويت',
          ancestralCity: '',
          armenianAncestralCity: '',
          arabicAncestralCity: '',
          route: '',
          armenianRoute: '',
          arabicRoute: '',
          quote:
            'Before the war, I had already come to Armenia as a tourist. When I was here for tourism, Armenia was very very different. It was so beautiful to my eyes, but when we came because of the problems from the war it was completely different to my eyes. I could not see the beauty of the country...But we were able to overcome. Now it is not like the beginning. Bit by bit we learned. We created a community here.',
          shortVideoLink: '',
          fullVideoLink: '',
          img: ritaSarkisian,
          video: video1,
        },
        {
          name: 'Ani Avakian',
          armenianName: 'Անի Ավագյան ',
          arabicName: '',
          cityOfResidence: 'Yerevan, Armenia',
          armenianCityOfResidence: 'Երեւան, Հայաստան',
          arabicCityOfResidence: 'يريفان، أرمينيا',
          age: 51,
          armenianAge: 51,
          arabicAge: 51,
          birthplace: 'Aleppo, Syria',
          armenianBirthplace: 'Հալէպ, Սուրիա',
          arabicBirthplace: 'حلب، سوريا',
          ancestralCity: '',
          armenianAncestralCity: '',
          arabicAncestralCity: '',
          route: '',
          armenianRoute: '',
          arabicRoute: '',
          quote:
            'Armenian education in the Diaspora has a big responsibility. You should not only teach Armenian reading and writing or grammar and literature. You have to familiarize them with the nation’s values and the nation’s individuals who display them, so that they can feel proud and grounded...If the teacher can dive into cultural topics, especially because our culture is so beautiful, then you can make the classes more interesting and make the students more connected to the subject. I tried to do that as an Armenian teacher for 10 years.',
          shortVideoLink: '',
          fullVideoLink: '',
          img: aniAvakian,
          video: video1,
        },
        {
          name: 'Danya Dashyan',
          armenianName: 'Տանյա Դաշյան',
          arabicName: '',
          cityOfResidence: 'Yerevan, Armenia',
          armenianCityOfResidence: 'Երեւան, Հայաստան',
          arabicCityOfResidence: 'يريفان، أرمينيا',
          age: 56,
          armenianAge: 56,
          arabicAge: 56,
          birthplace: 'Baku, Azerbaijan',
          armenianBirthplace: 'Բաքու, Ադրբեջան',
          arabicBirthplace: 'باكو،أذربيجان',
          ancestralCity: '',
          armenianAncestralCity: '',
          arabicAncestralCity: '',
          route: '',
          armenianRoute: '',
          arabicRoute: '',
          quote:
            'We wish there was more Social Housing in Armenia so that Syrian Armenians won’t have the problem of paying rent. It may not be their own property but at least they will live without paying rent. ',
          shortVideoLink: '',
          fullVideoLink: '',
          img: danyaDashyan,
          video: video1,
        },
        {
          name: 'Vartanoush Shitilian',
          armenianName: 'Վարդանուշ Շիթիլեան',
          arabicName: '',
          cityOfResidence: 'Yerevan, Armenia',
          armenianCityOfResidence: 'Երեւան, Հայաստան',
          arabicCityOfResidence: 'يريفان، أرمينيا',
          age: 93,
          armenianAge: 93,
          arabicAge: 93,
          birthplace: 'Azaz, Syria',
          armenianBirthplace: 'Ազազ, Սուրիա',
          arabicBirthplace: 'أعزاز‎، سوريا',
          ancestralCity: 'Kilis',
          armenianAncestralCity: 'Քիլիս',
          arabicAncestralCity: 'كلز',
          route: '',
          armenianRoute: '',
          arabicRoute: '',
          quote:
            'One day, we were going to school in Afrin. There the Muslims were saying “Allahu Akbar.” At first they did not have anything like a church, so they were doing the prayers at their houses. I was going to school and I saw them men praying “Allahu Akbar” “Allahu Akbar.” So I also sat with them and did the prayers with them. The teacher saw that I was doing the prayers with them when it was time for school. So I went to school and the teacher asked me what I was doing. I said they were standing and kneeling so I did the same. She gave me a good spank. She told me not to do it again. She said they are Muslim and could hit me. She said I was mocking them.',
          shortVideoLink: 'https://www.youtube.com/embed/_nJY0PZvgQw',
          fullVideoLink: '',
          img: vartanoushShitilian,
          video: video1,
        },
        {
          name: 'Toros Toranian',
          armenianName: 'Թորոս Թորանեան',
          arabicName: '',
          cityOfResidence: 'Yerevan, Armenia',
          armenianCityOfResidence: 'Երեւան, Հայաստան',
          arabicCityOfResidence: 'يريفان، أرمينيا',
          age: 89,
          armenianAge: 89,
          arabicAge: 89,
          birthplace: 'Aleppo, Syria',
          armenianBirthplace: 'Հալէպ, Սուրիա',
          arabicBirthplace: 'حلب، سوريا',
          ancestralCity: 'Sassoun',
          armenianAncestralCity: 'Սասուն',
          arabicAncestralCity: 'ساسون',
          route: 'Car to Beirut, Airplane to Yerevan',
          armenianRoute: 'Ինքնաշարժ դէպի Պէյրութ, Օդանաւ դէպի Երեւան',
          arabicRoute: 'سيارة إلی بيروت وطائرة إلی يريفان ',
          quote:
            "In my childhood years, we never interacted with Arabs. Why? Because all the Armenians were living at the same place. Everything was Armenian, the shopkeeper, the baker, the cobbler, the tailor. We did not need anything else. Armenians were living collectively, with each other...At the school, when the Arab teacher used to come and say, 'This is an Arabic Country.' We didn't understand, what does it mean? What is that Arabic country?",
          shortVideoLink: 'https://www.youtube.com/embed/iOwNwXy_nBQ',
          fullVideoLink: '',
          img: torosToranian,
          video: video1,
        },
        {
          name: 'Sevan Torosian',
          armenianName: 'Սեւան Թորոսեան',
          arabicName: '',
          cityOfResidence: 'Yerevan, Armenia',
          armenianCityOfResidence: 'Երեւան, Հայաստան',
          arabicCityOfResidence: 'يريفان، أرمينيا',
          age: 40,
          armenianAge: 40,
          arabicAge: 40,
          birthplace: 'Aleppo, Syria',
          armenianBirthplace: 'Հալէպ, Սուրիա',
          arabicBirthplace: 'حلب، سوريا',
          ancestralCity: 'Urfa and Ainteb',
          armenianAncestralCity: 'Ուրֆա եւ Այնթապ',
          arabicAncestralCity: ' أورفة وعنتاب',
          route: 'Bus to Beirut, Airplane to Yerevan',
          armenianRoute: 'Ավտոպուս դէպի Պէյրութ, Օդանաւ դէպի Երեւան',
          arabicRoute: 'أتوبيس إلی بيروت وطائرة إلی يريفان ',
          quote:
            'Armenia is like your father, who gave you your name. And Syria is like your mother who took care of you for years. ',
          shortVideoLink: 'https://www.youtube.com/embed/7V8QIV-WCSs',
          fullVideoLink: '',
          img: sevanTorosian,
          video: video1,
        },
        {
          name: 'Krikor Stepanian',
          armenianName: 'Գրիգոր Սըտբնեան',
          arabicName: '',
          cityOfResidence: 'Yerevan, Armenia',
          armenianCityOfResidence: 'Երեւան, Հայաստան',
          arabicCityOfResidence: 'يريفان، أرمينيا',
          age: 54,
          armenianAge: 54,
          arabicAge: 54,
          birthplace: 'Aleppo, Syria',
          armenianBirthplace: 'Հալէպ, Սուրիա',
          arabicBirthplace: 'حلب، سوريا',
          ancestralCity: 'Ainteb and Konya',
          armenianAncestralCity: 'Քոնիա եւ Այնթապ ',
          arabicAncestralCity: '  قونية وعنتاب',
          route: 'Bus through Turkey and Georgia to Armenia',
          armenianRoute:
            'Ավտոպուս դէպի Հայաստան Թուրքական եւ Վրացական ճամբայով',
          arabicRoute: 'أتوبيس إلی يريفان بطريق تركيا وجورجيا',
          quote:
            'They uncovered my eyes and untied my hands and put me on my knees. They told me to pray. I prayed their prayers, but inside I was saying “Oh God, I am in your hands not in their hands. You will save me, not them.”',
          shortVideoLink: 'https://www.youtube.com/embed/R_CnoXa6t2Q',
          fullVideoLink: '',
          img: krikorStepanian,
          video: video1,
        },
        {
          name: 'Dzovag Soghomonian',
          armenianName: 'Ծովակ Սողոմոնեան',
          arabicName: '',
          cityOfResidence: 'Yerevan, Armenia',
          armenianCityOfResidence: 'Երեւան, Հայաստան',
          arabicCityOfResidence: 'يريفان، أرمينيا',
          age: 26,
          armenianAge: 26,
          arabicAge: 26,
          birthplace: 'Damascus, Syria',
          armenianBirthplace: 'Դամասկոս, Սուրիա',
          arabicBirthplace: 'دمشق، سوريا',
          ancestralCity: '',
          armenianAncestralCity: '',
          arabicAncestralCity: '',
          route: '',
          armenianRoute: '',
          arabicRoute: '',
          quote:
            'Now, I do not consider that I moved to Armenia because of the war. I moved to Armenia because I really want to. I am a repatriate. That is what I consider myself now. I know the war happened and it was not beautiful. But it is kind of a destiny to come back to Armenia....I know it was not a beautiful destiny, but maybe it is somehow. Maybe if there was no war, I would not have moved to Armenia. But I am here, so it is a beautiful destiny. So I continue surviving and living these beautiful moments in my homeland.',
          shortVideoLink: 'https://www.youtube.com/embed/WzIvbg_dH6E',
          fullVideoLink: '',
          img: dzovagSoghomonian,
          video: video1,
        },
        {
          name: 'Vahram DerOhanian',
          armenianName: 'Վահրամ ՏէրՕհանեան',
          arabicName: '',
          cityOfResidence: 'Yerevan, Armenia',
          armenianCityOfResidence: 'Երեւան, Հայաստան',
          arabicCityOfResidence: 'يريفان، أرمينيا',
          age: 52,
          armenianAge: 52,
          arabicAge: 52,
          birthplace: 'Aleppo, Syria',
          armenianBirthplace: 'Հալէպ, Սուրիա',
          arabicBirthplace: 'حلب، سوريا',
          ancestralCity: 'Kilis and Kharpert',
          armenianAncestralCity: 'Քիլիս եւ Խարբերդ',
          arabicAncestralCity: 'كلز وخربوط',
          route: 'Bus to Beirut, Airplane to Yerevan',
          armenianRoute: 'Ավտոպուս դէպի Պէյրութ, Օդանաւ դէպի Երեւան',
          arabicRoute: 'أتوبيس إلی بيروت وطائرة إلی يريفان ',
          quote:
            'In Armenia, locals asked why is my stand called Spitak, and I said as a memorial to the earthquake victims. They says “Oh you remember us Armenians?” Of course, we would never forget. We remembered it so much from Aleppo, that is why I have the name now.',
          shortVideoLink: '',
          fullVideoLink: '',
          img: vahramDerOhanian,
          video: video1,
        },
        {
          name: 'Artsakh',
          armenianName: 'Արցախ',
          arabicName: '',
          cityOfResidence: 'Europe',
          armenianCityOfResidence: 'Եվրոպա',
          arabicCityOfResidence: 'أوروبا',
          age: 56,
          armenianAge: 56,
          arabicAge: 56,
          birthplace: 'Aleppo, Syria',
          armenianBirthplace: 'Հալէպ, Սուրիա',
          arabicBirthplace: 'حلب، سوريا',
          ancestralCity: '',
          armenianAncestralCity: '',
          arabicAncestralCity: '',
          route: '',
          armenianRoute: '',
          arabicRoute: '',
          quote:
            'Sultan Abdul Hamid said there will only be enough Armenians to put in museums....We proved that wrong by prospering...and preserving our Armenian letters and creating schools. Wherever Armenians went they started schools, and those schools are the reasons Armenians preserved and protected their language, culture, nation, and beliefs.',
          shortVideoLink: '',
          fullVideoLink: '',
          img: rerooted,
          video: video1,
        },
        {
          name: 'Lusin Mkhlmeljian',
          armenianName: 'Լուսին Մխմելճեան',
          arabicName: '',
          cityOfResidence: 'Yerevan, Armenia',
          armenianCityOfResidence: 'Երեւան, Հայաստան',
          arabicCityOfResidence: 'يريفان، أرمينيا',
          age: 51,
          armenianAge: 51,
          arabicAge: 51,
          birthplace: 'Aleppo, Syria',
          armenianBirthplace: 'Հալէպ, Սուրիա',
          arabicBirthplace: 'حلب، سوريا',
          ancestralCity: 'Ainteb',
          armenianAncestralCity: 'Այնթապ',
          arabicAncestralCity: 'عنتاب',
          route: 'Airplane to Yerevan, Armenia',
          armenianRoute: 'Օդանաւ դէպի Երեւան',
          arabicRoute: 'طائرة إلی يريفان',
          quote:
            'When we had just arrived to Armenia, I had a lot of anxiety. I wanted to do something to forget all that I had seen and lived through. By giving myself work, I wanted to forget all of that. And I needed to live in Armenia where life is expensive, so we busied ourselves with work. And I did it with love. From 10 in the morning until 11 at night, I was on my feet and I couldn’t even feel tired because we needed to do something, move forward, make money, and live.',
          shortVideoLink: '',
          fullVideoLink: 'https://www.youtube.com/embed/UYqHImOaNno',
          img: lusinMkhlmeljian,
          video: video1,
        },
        {
          name: 'Mayda Hindoyan',
          armenianName: 'Մայտա Հինտոյան',
          arabicName: '',
          cityOfResidence: 'Yerevan, Armenia',
          armenianCityOfResidence: 'Երեւան, Հայաստան',
          arabicCityOfResidence: 'يريفان، أرمينيا',
          age: 66,
          armenianAge: 66,
          arabicAge: 66,
          birthplace: 'Aleppo, Syria',
          armenianBirthplace: 'Հալէպ, Սուրիա',
          arabicBirthplace: 'حلب، سوريا',
          ancestralCity: 'Ainteb',
          armenianAncestralCity: 'Այնթապ',
          arabicAncestralCity: 'عنتاب',
          route: 'Airplane to Beirut, Airplane to Yerevan',
          armenianRoute: 'Օդանաւ դէպի Պէյրութ, Օդանաւ դէպի Երեւան',
          arabicRoute: 'طائرة إلی بيروت وطائرة إلی يريفان ',
          quote:
            'I used to dream of at least visiting or even living in Armenia. When people visited Armenia from Syria before the war, I would tell them to look at Armenia with their eyes for me.  I always loved it. I say that it is like heaven here.t  would only be better if my family, and all my children were here so I would not have to miss anybody. At my age family is what is important and to have good health to enjoy them. ',
          shortVideoLink: '',
          fullVideoLink: 'https://www.youtube.com/embed/H_hHCWlHb4k',
          img: maydaHindoyan,
          video: video1,
        },
        {
          name: 'Vicky Masrie',
          armenianName: 'Վիքի Մասրի',
          arabicName: '',
          cityOfResidence: 'Yerevan, Armenia',
          armenianCityOfResidence: 'Երեւան, Հայաստան',
          arabicCityOfResidence: 'يريفان، أرمينيا',
          age: 25,
          armenianAge: 25,
          arabicAge: 25,
          birthplace: 'Aleppo, Syria',
          armenianBirthplace: 'Հալէպ, Սուրիա',
          arabicBirthplace: 'حلب، سوريا',
          ancestralCity: 'Ainteb',
          armenianAncestralCity: 'Այնթապ',
          arabicAncestralCity: 'عنتاب',
          route: 'Airplane to Beirut, Airplane to Yerevan',
          armenianRoute: 'Օդանաւ դէպի Պէյրութ, Օդանաւ դէպի Երեւան',
          arabicRoute: 'طائرة إلی بيروت وطائرة إلی يريفان ',
          quote:
            'For me I feel like I have come back to our homeland, although I miss Aleppo a lot. Not Syria because Syria is just a country to me. Aleppo is my birthplace and I miss it a lot..At the beginning I didn’t feel like Yerevan was home. But when I went out of Yerevan and came back, I knew that this is home too. Now I have two homes, Aleppo and Yerevan.',
          shortVideoLink: '',
          fullVideoLink: 'https://www.youtube.com/embed/H_hHCWlHb4k',
          img: vickyMasrie,
          video: video1,
        },
        {
          name: 'Toros Ayranjian',
          armenianName: 'Թորոս Այրանճեան',
          arabicName: '',
          cityOfResidence: 'Yerevan, Armenia',
          armenianCityOfResidence: 'Երեւան, Հայաստան',
          arabicCityOfResidence: 'يريفان، أرمينيا',
          age: 75,
          armenianAge: 75,
          arabicAge: 75,
          birthplace: 'Aleppo, Syria',
          armenianBirthplace: 'Հալէպ, Սուրիա',
          arabicBirthplace: 'حلب، سوريا',
          ancestralCity: 'Marash',
          armenianAncestralCity: 'Մարաշ',
          arabicAncestralCity: 'مرعش',
          route: 'Bus to Beirut, Airplane to Yerevan',
          armenianRoute: 'Ավտոպուս դէպի Պէյրութ, Օդանաւ դէպի Երեւան',
          arabicRoute: 'أتوبيس إلی بيروت وطائرة إلی يريفان ',
          quote: 'We were married 50 years and 4 months.',
          shortVideoLink: 'https://www.youtube.com/embed/DiCfaPu0hds',
          fullVideoLink: 'https://www.youtube.com/embed/sQkWmaDANto',
          img: takouhiBedros,
          video: video1,
        },
        {
          name: 'Takouhi Bedros',
          armenianName: 'Թագուհի Պետրոս ',
          arabicName: '',
          cityOfResidence: 'Yerevan, Armenia',
          armenianCityOfResidence: 'Երեւան, Հայաստան',
          arabicCityOfResidence: 'يريفان، أرمينيا',
          age: 63,
          armenianAge: 63,
          arabicAge: 63,
          birthplace: 'Der Zor, Syria',
          armenianBirthplace: 'Տէր Զօր, Սուրիա',
          arabicBirthplace: 'دير الزور، سوريا',
          ancestralCity: 'Dikranagerd and Kharpert',
          armenianAncestralCity: 'եւ Խարբերդ',
          arabicAncestralCity: '  وخربوط',
          route: 'Bus to Beirut, Airplane to Yerevan',
          armenianRoute: 'Ավտոպուս դէպի Պէյրութ, Օդանաւ դէպի Երեւան',
          arabicRoute: 'أتوبيس إلی بيروت وطائرة إلی يريفان ',
          quote:
            'My husband’s doctors had all fled from Syria, and he has heart problems. So we thought to leave to our country, Armenia. We could be satisfied with just a piece of bread. What else could we do at our age?',
          shortVideoLink: 'https://www.youtube.com/embed/DiCfaPu0hds',
          fullVideoLink: 'https://www.youtube.com/embed/sQkWmaDANto',
          img: takouhiBedros,
          video: video1,
        },
        {
          name: 'Hagop Atikian',
          armenianName: 'Հակոբ Աթիգեան',
          arabicName: '',
          cityOfResidence: 'Yerevan, Armenia',
          armenianCityOfResidence: 'Երեւան, Հայաստան',
          arabicCityOfResidence: 'يريفان، أرمينيا',
          age: 44,
          armenianAge: 44,
          arabicAge: 44,
          birthplace: 'Aleppo, Syria',
          armenianBirthplace: 'Հալէպ, Սուրիա',
          arabicBirthplace: 'حلب، سوريا',
          ancestralCity: 'Musaler and Iskanderun',
          armenianAncestralCity: 'Մուսա լեռ եւ Ալեքսանդրետտա',
          arabicAncestralCity: 'جبل موسی والإسكندرونة‎',
          route: 'Airplane to Yerevan then car to Artsakh',
          armenianRoute: 'Օդանաւ դէպի Երեւան եւ ինքնաշարժ դէպի Արցախ',
          arabicRoute: 'طائرة إلی يريفان وسيارة إلی قرة باغ',
          quote:
            "It was my wife's love and us being hand-in-hand that made it possible for us to get back on our feet. Otherwise it would have been too hard.",
          shortVideoLink: 'https://www.youtube.com/embed/AixpZraJi54',
          fullVideoLink: 'https://www.youtube.com/embed/OduWA8zCjec',
          img: hagopAtikian,
          video: video1,
        },
        {
          name: 'Linda Arakel',
          armenianName: 'Լինտա Առաքել',
          arabicName: '',
          cityOfResidence: 'Yerevan, Armenia',
          armenianCityOfResidence: 'Երեւան, Հայաստան',
          arabicCityOfResidence: 'يريفان، أرمينيا',
          age: 32,
          armenianAge: 32,
          arabicAge: 32,
          birthplace: 'Aleppo, Syria',
          armenianBirthplace: 'Հալէպ, Սուրիա',
          arabicBirthplace: 'حلب، سوريا',
          ancestralCity: 'Sassoun',
          armenianAncestralCity: 'Սասուն',
          arabicAncestralCity: 'ساسون',
          route: 'Airplane to Yerevan then car to Artsakh',
          armenianRoute: 'Օդանաւ դէպի Երեւան եւ ինքնաշարժ դէպի Արցախ',
          arabicRoute: 'طائرة إلی يريفان وسيارة إلی قرة باغ',
          quote:
            'The driver said, "but we are all men." I said, "I am a man too" I\'ll cover my hair and come sit with you, I said. "If you die, I die, if you live you live, I am your sister, I just came to drive with you, if you\'re going, I am coming with you."',
          shortVideoLink: 'https://www.youtube.com/embed/AixpZraJi54',
          fullVideoLink: 'https://www.youtube.com/embed/OduWA8zCjec',
          img: lindaArakel,
          video: video1,
        },
        {
          name: 'Eva Zadkian',
          armenianName: 'Եվա Զատիկեան',
          arabicName: '',
          cityOfResidence: 'Yerevan, Armenia',
          armenianCityOfResidence: 'Երեւան, Հայաստան',
          arabicCityOfResidence: 'يريفان، أرمينيا',
          age: 44,
          armenianAge: 44,
          arabicAge: 44,
          birthplace: 'Kuwait',
          armenianBirthplace: 'Քուվեյթ',
          arabicBirthplace: 'الكويت',
          ancestralCity: '',
          armenianAncestralCity: '',
          arabicAncestralCity: '',
          route: '',
          armenianRoute: '',
          arabicRoute: '',
          quote: '',
          shortVideoLink: '',
          fullVideoLink: '',
          img: arshoughKakoyian,
          video: video1,
        },
        {
          name: 'Arshough Kakoyian',
          armenianName: 'Արշուկ Քաքոյան',
          arabicName: '',
          cityOfResidence: 'Yerevan, Armenia',
          armenianCityOfResidence: 'Երեւան, Հայաստան',
          arabicCityOfResidence: 'يريفان، أرمينيا',
          age: 50,
          armenianAge: 50,
          arabicAge: 50,
          birthplace: 'Aleppo, Syria',
          armenianBirthplace: 'Հալէպ, Սուրիա',
          arabicBirthplace: 'حلب، سوريا',
          ancestralCity: '',
          armenianAncestralCity: '',
          arabicAncestralCity: '',
          route: '',
          armenianRoute: '',
          arabicRoute: '',
          quote: '',
          shortVideoLink: '',
          fullVideoLink: '',
          img: arshoughKakoyian,
          video: video1,
        },
        {
          name: 'Dikranuhi Jrazian',
          armenianName: 'Տիքրանուհի Ճրազեան',
          arabicName: '',
          cityOfResidence: 'Yerevan, Armenia',
          armenianCityOfResidence: 'Երեւան, Հայաստան',
          arabicCityOfResidence: 'يريفان، أرمينيا',
          age: 65,
          armenianAge: 65,
          arabicAge: 65,
          birthplace: 'Aleppo, Syria',
          armenianBirthplace: 'Հալէպ, Սուրիա',
          arabicBirthplace: 'حلب، سوريا',
          ancestralCity: '',
          armenianAncestralCity: '',
          arabicAncestralCity: '',
          route: '',
          armenianRoute: '',
          arabicRoute: '',
          quote: '',
          shortVideoLink: '',
          fullVideoLink: '',
          img: dikranuhiJrazian,
          video: video1,
        },
        {
          name: 'Hovsep Kazanjian',
          armenianName: 'Հովսեփ Գազանճեան',
          arabicName: '',
          cityOfResidence: 'Yerevan, Armenia',
          armenianCityOfResidence: 'Երեւան, Հայաստան',
          arabicCityOfResidence: 'يريفان، أرمينيا',
          age: 25,
          armenianAge: 25,
          arabicAge: 25,
          birthplace: 'Aleppo, Syria',
          armenianBirthplace: 'Հալէպ, Սուրիա',
          arabicBirthplace: 'حلب، سوريا',
          ancestralCity: '',
          armenianAncestralCity: '',
          arabicAncestralCity: '',
          route: '',
          armenianRoute: '',
          arabicRoute: '',
          quote: '',
          shortVideoLink: '',
          fullVideoLink: '',
          img: hovsepKazanjian,
          video: video1,
        },
        {
          name: 'Armine Arabatlian',
          armenianName: 'Արմինե Արապաթլեան',
          arabicName: '',
          cityOfResidence: 'USA',
          armenianCityOfResidence: 'Ամերիկա',
          arabicCityOfResidence: 'الولايات المتحدة',
          age: 20,
          armenianAge: 20,
          arabicAge: 20,
          birthplace: 'USA',
          armenianBirthplace: 'Ամերիկա',
          arabicBirthplace: 'الولايات المتحدة',
          ancestralCity: '',
          armenianAncestralCity: '',
          arabicAncestralCity: '',
          route: '',
          armenianRoute: '',
          arabicRoute: '',
          quote: '',
          shortVideoLink: '',
          fullVideoLink: '',
          img: sakoSarkisian,
          video: video1,
        },
        {
          name: 'Sako Sarkisian',
          armenianName: 'Սաքո Սարգիսեան',
          arabicName: 'ساكو سركسيان',
          cityOfResidence: 'Yerevan, Armenia',
          armenianCityOfResidence: 'Երեւան, Հայաստան',
          arabicCityOfResidence: 'يريفان، أرمينيا',
          age: 22,
          armenianAge: 22,
          arabicAge: 22,
          birthplace: 'Aleppo, Syria',
          armenianBirthplace: 'Հալէպ, Սուրիա',
          arabicBirthplace: 'حلب، سوريا',
          ancestralCity: '',
          armenianAncestralCity: '',
          arabicAncestralCity: '',
          route: '',
          armenianRoute: '',
          arabicRoute: '',
          quote: '',
          shortVideoLink: '',
          fullVideoLink: '',
          img: sakoSarkisian,
          video: video1,
        },
        {
          name: 'Sophi Nersisyan',
          armenianName: 'Սոֆի Ներսիսյան',
          arabicName: '',
          cityOfResidence: 'Yerevan, Armenia',
          armenianCityOfResidence: 'Երեւան, Հայաստան',
          arabicCityOfResidence: 'يريفان، أرمينيا',
          age: 42,
          armenianAge: 42,
          arabicAge: 42,
          birthplace: 'Yerevan, Armenia',
          armenianBirthplace: 'Երեւան, Հայաստան',
          arabicBirthplace: 'يريفان، أرمينيا',
          ancestralCity: '',
          armenianAncestralCity: '',
          arabicAncestralCity: '',
          route: '',
          armenianRoute: '',
          arabicRoute: '',
          quote: '',
          shortVideoLink: '',
          fullVideoLink: '',
          img: sophiNersisyan,
          video: video1,
        },
        {
          name: 'Anahid Sarafian',
          armenianName: 'Անահիտ Սարաֆեան',
          arabicName: '',
          cityOfResidence: 'Yerevan, Armenia',
          armenianCityOfResidence: 'Երեւան, Հայաստան',
          arabicCityOfResidence: 'يريفان، أرمينيا',
          age: 76,
          armenianAge: 76,
          arabicAge: 76,
          birthplace: 'Aleppo, Syria',
          armenianBirthplace: 'Հալէպ, Սուրիա',
          arabicBirthplace: 'حلب، سوريا',
          ancestralCity: '',
          armenianAncestralCity: '',
          arabicAncestralCity: '',
          route: '',
          armenianRoute: '',
          arabicRoute: '',
          quote: '',
          shortVideoLink: '',
          fullVideoLink: '',
          img: rerooted,
          video: video1,
        },
        {
          name: 'Takouhi Naljain',
          armenianName: 'Թագուհի Նալճեան',
          arabicName: '',
          cityOfResidence: 'Yerevan, Armenia',
          armenianCityOfResidence: 'Երեւան, Հայաստան',
          arabicCityOfResidence: 'يريفان، أرمينيا',
          age: 55,
          armenianAge: 55,
          arabicAge: 55,
          birthplace: 'Aleppo, Syria',
          armenianBirthplace: 'Հալէպ, Սուրիա',
          arabicBirthplace: 'حلب، سوريا',
          ancestralCity: '',
          armenianAncestralCity: '',
          arabicAncestralCity: '',
          route: '',
          armenianRoute: '',
          arabicRoute: '',
          quote: '',
          shortVideoLink: '',
          fullVideoLink: '',
          img: rerooted,
          video: video1,
        },
        {
          name: 'Eliza Bazarjian',
          armenianName: 'էլիզա Պազարճեան',
          arabicName: '',
          cityOfResidence: 'Yerevan, Armenia',
          armenianCityOfResidence: 'Երեւան, Հայաստան',
          arabicCityOfResidence: 'يريفان، أرمينيا',
          age: 82,
          armenianAge: 82,
          arabicAge: 82,
          birthplace: 'Aleppo, Syria',
          armenianBirthplace: 'Հալէպ, Սուրիա',
          arabicBirthplace: 'حلب، سوريا',
          ancestralCity: '',
          armenianAncestralCity: '',
          arabicAncestralCity: '',
          route: '',
          armenianRoute: '',
          arabicRoute: '',
          quote: '',
          shortVideoLink: '',
          fullVideoLink: '',
          img: anitaBoghoyan,
          video: video1,
        },
        {
          name: 'Varujan Boghoyan',
          armenianName: 'Վարուժան Պողոեան',
          arabicName: '',
          cityOfResidence: 'Yerevan, Armenia',
          armenianCityOfResidence: 'Երեւան, Հայաստան',
          arabicCityOfResidence: 'يريفان، أرمينيا',
          age: 52,
          armenianAge: 52,
          arabicAge: 52,
          birthplace: 'Aleppo, Syria',
          armenianBirthplace: 'Հալէպ, Սուրիա',
          arabicBirthplace: 'حلب، سوريا',
          ancestralCity: '',
          armenianAncestralCity: '',
          arabicAncestralCity: '',
          route: '',
          armenianRoute: '',
          arabicRoute: '',
          quote: '',
          shortVideoLink: '',
          fullVideoLink: '',
          img: anitaBoghoyan,
          video: video1,
        },
        {
          name: 'Anita Boghoyan',
          armenianName: 'Անիդա Պողոեան',
          arabicName: '',
          cityOfResidence: 'Yerevan, Armenia',
          armenianCityOfResidence: 'Երեւան, Հայաստան',
          arabicCityOfResidence: 'يريفان، أرمينيا',
          age: 50,
          armenianAge: 50,
          arabicAge: 50,
          birthplace: 'Aleppo, Syria',
          armenianBirthplace: 'Հալէպ, Սուրիա',
          arabicBirthplace: 'حلب، سوريا',
          ancestralCity: '',
          armenianAncestralCity: '',
          arabicAncestralCity: '',
          route: '',
          armenianRoute: '',
          arabicRoute: '',
          quote: '',
          shortVideoLink: '',
          fullVideoLink: '',
          img: anitaBoghoyan,
          video: video1,
        },
        {
          name: 'Natela Stepanian',
          armenianName: 'Նաթելա Ստեփանյան',
          arabicName: '',
          cityOfResidence: 'Gyumri, Armenia',
          armenianCityOfResidence: 'Գյումրի, Հայաստան',
          arabicCityOfResidence: 'غيومري، أرمينيا',
          age: 33,
          armenianAge: 33,
          arabicAge: 33,
          birthplace: 'Gyumri, Armenia',
          armenianBirthplace: 'Գյումրի, Հայաստան',
          arabicBirthplace: 'غيومري، أرمينيا',
          ancestralCity: '',
          armenianAncestralCity: '',
          arabicAncestralCity: '',
          route: '',
          armenianRoute: '',
          arabicRoute: '',
          quote: '',
          shortVideoLink: '',
          fullVideoLink: '',
          img: natelaStepanian,
          video: video1,
        },
        {
          name: 'Hayasa Tahmazyan',
          armenianName: 'Հայասա Թահմազեան',
          arabicName: '',
          cityOfResidence: 'Echmiadzin, Armenia',
          armenianCityOfResidence: 'Էջմիածին, Հայաստան',
          arabicCityOfResidence: 'إتشميادزين، أرمينيا',
          age: 28,
          armenianAge: 28,
          arabicAge: 28,
          birthplace: 'Armenia',
          armenianBirthplace: 'Հայաստան',
          arabicBirthplace: 'أرمينيا',
          ancestralCity: '',
          armenianAncestralCity: '',
          arabicAncestralCity: '',
          route: '',
          armenianRoute: '',
          arabicRoute: '',
          quote: '',
          shortVideoLink: '',
          fullVideoLink: '',
          img: hayasaTahmazyan,
          video: video1,
        },
        {
          name: 'Kevork Mouradian',
          armenianName: 'Գէորգ Մուրատեան',
          arabicName: '',
          cityOfResidence: 'Yerevan, Armenia',
          armenianCityOfResidence: 'Երեւան, Հայաստան',
          arabicCityOfResidence: 'يريفان، أرمينيا',
          age: 40,
          armenianAge: 40,
          arabicAge: 40,
          birthplace: 'Aleppo, Syria',
          armenianBirthplace: 'Հալէպ, Սուրիա',
          arabicBirthplace: 'حلب، سوريا',
          ancestralCity: '',
          armenianAncestralCity: '',
          arabicAncestralCity: '',
          route: '',
          armenianRoute: '',
          arabicRoute: '',
          quote: '',
          shortVideoLink: '',
          fullVideoLink: '',
          img: kevorkMouradian,
          video: video1,
        },
        {
          name: 'Garen Balkhian',
          armenianName: 'Կարեն Պալխեան',
          arabicName: '',
          cityOfResidence: 'Yerevan, Armenia',
          armenianCityOfResidence: 'Երեւան, Հայաստան',
          arabicCityOfResidence: 'يريفان، أرمينيا',
          age: 21,
          armenianAge: 21,
          arabicAge: 21,
          birthplace: 'Aleppo, Syria',
          armenianBirthplace: 'Հալէպ, Սուրիա',
          arabicBirthplace: 'حلب، سوريا',
          ancestralCity: '',
          armenianAncestralCity: '',
          arabicAncestralCity: '',
          route: '',
          armenianRoute: '',
          arabicRoute: '',
          quote: '',
          shortVideoLink: '',
          fullVideoLink: '',
          img: garenBalkhian,
          video: video1,
        },
        {
          name: 'Nazaret Melkonian',
          armenianName: 'Նազարէթ Մէլքոնեան',
          arabicName: '',
          cityOfResidence: 'Yerevan, Armenia',
          armenianCityOfResidence: 'Երեւան, Հայաստան',
          arabicCityOfResidence: 'يريفان، أرمينيا',
          age: 62,
          armenianAge: 62,
          arabicAge: 62,
          birthplace: 'Aleppo, Syria',
          armenianBirthplace: 'Հալէպ, Սուրիա',
          arabicBirthplace: 'حلب، سوريا',
          ancestralCity: '',
          armenianAncestralCity: '',
          arabicAncestralCity: '',
          route: '',
          armenianRoute: '',
          arabicRoute: '',
          quote: '',
          shortVideoLink: '',
          fullVideoLink: '',
          img: nazaretMelkonian,
          video: video1,
        },
        {
          name: 'Lusin Madarjian',
          armenianName: 'Լուսին Մատարճյան',
          arabicName: '',
          cityOfResidence: 'Yerevan, Armenia',
          armenianCityOfResidence: 'Երեւան, Հայաստան',
          arabicCityOfResidence: 'يريفان، أرمينيا',
          age: 94,
          armenianAge: 94,
          arabicAge: 94,
          birthplace: 'Aleppo, Syria',
          armenianBirthplace: 'Հալէպ, Սուրիա',
          arabicBirthplace: 'حلب، سوريا',
          ancestralCity: '',
          armenianAncestralCity: '',
          arabicAncestralCity: '',
          route: '',
          armenianRoute: '',
          arabicRoute: '',
          quote: '',
          shortVideoLink: '',
          fullVideoLink: '',
          img: lusinMadarjian,
          video: video1,
        },
        {
          name: 'Narine Madarjian',
          armenianName: 'Նարինէ Մատարճյան',
          arabicName: '',
          cityOfResidence: 'Yerevan, Armenia',
          armenianCityOfResidence: 'Երեւան, Հայաստան',
          arabicCityOfResidence: 'يريفان، أرمينيا',
          age: 91,
          armenianAge: 91,
          arabicAge: 91,
          birthplace: 'Raqqa, Syria',
          armenianBirthplace: 'Ռաքքա, Սուրիա',
          arabicBirthplace: 'الرقة، سوريا',
          ancestralCity: '',
          armenianAncestralCity: '',
          arabicAncestralCity: '',
          route: '',
          armenianRoute: '',
          arabicRoute: '',
          quote: '',
          shortVideoLink: '',
          fullVideoLink: '',
          img: narineMadarjian,
          video: video1,
        },
        {
          name: 'Sevan Madarjian',
          armenianName: 'Սեւան Մատարճիան',
          arabicName: '',
          cityOfResidence: 'Yerevan, Armenia',
          armenianCityOfResidence: 'Երեւան, Հայաստան',
          arabicCityOfResidence: 'يريفان، أرمينيا',
          age: 89,
          armenianAge: 89,
          arabicAge: 89,
          birthplace: 'Raqqa, Syria',
          armenianBirthplace: 'Ռաքքա, Սուրիա',
          arabicBirthplace: 'الرقة، سوريا',
          ancestralCity: '',
          armenianAncestralCity: '',
          arabicAncestralCity: '',
          route: '',
          armenianRoute: '',
          arabicRoute: '',
          quote: '',
          shortVideoLink: '',
          fullVideoLink: '',
          img: sevanMadarjian,
          video: video1,
        },
        {
          name: 'Hovsep Madarjian',
          armenianName: 'Յովսէփ Մատարճյան',
          arabicName: '',
          cityOfResidence: 'Yerevan, Armenia',
          armenianCityOfResidence: 'Երեւան, Հայաստան',
          arabicCityOfResidence: 'يريفان، أرمينيا',
          age: 51,
          armenianAge: 51,
          arabicAge: 51,
          birthplace: 'Qamishli, Syria',
          armenianBirthplace: 'Քամիշլի, Սուրիա',
          arabicBirthplace: ' القامشلي‎، سوريا',
          ancestralCity: '',
          armenianAncestralCity: '',
          arabicAncestralCity: '',
          route: '',
          armenianRoute: '',
          arabicRoute: '',
          quote: '',
          shortVideoLink: '',
          fullVideoLink: '',
          img: hovsepMadarjian,
          video: video1,
        },
        {
          name: 'Dzovig Ghazarian',
          armenianName: 'Ծովիկ Ղասզարյան',
          arabicName: '',
          cityOfResidence: 'Yerevan, Armenia',
          armenianCityOfResidence: 'Երեւան, Հայաստան',
          arabicCityOfResidence: 'يريفان، أرمينيا',
          age: 51,
          armenianAge: 51,
          arabicAge: 51,
          birthplace: 'Qamshli, Syria',
          armenianBirthplace: 'Քամիշլի, Սուրիա',
          arabicBirthplace: ' القامشلي‎، سوريا',
          ancestralCity: '',
          armenianAncestralCity: '',
          arabicAncestralCity: '',
          route: '',
          armenianRoute: '',
          arabicRoute: '',
          quote: '',
          shortVideoLink: '',
          fullVideoLink: '',
          img: dzovigGhazarian,
          video: video1,
        },
        {
          name: 'Kevork Sookiasian',
          armenianName: 'Գէորգ Սոգքէեասեան',
          arabicName: '',
          cityOfResidence: 'Yerevan, Armenia',
          armenianCityOfResidence: 'Երեւան, Հայաստան',
          arabicCityOfResidence: 'يريفان، أرمينيا',
          age: 22,
          armenianAge: 22,
          arabicAge: 22,
          birthplace: 'Aleppo, Syria',
          armenianBirthplace: 'Հալէպ, Սուրիա',
          arabicBirthplace: 'حلب، سوريا',
          ancestralCity: '',
          armenianAncestralCity: '',
          arabicAncestralCity: '',
          route: '',
          armenianRoute: '',
          arabicRoute: '',
          quote: '',
          shortVideoLink: '',
          fullVideoLink: '',
          img: kevorkSookiasian,
          video: video1,
        },
        {
          name: 'Azniv Kilislian Aghayegian',
          armenianName: 'Ազնիւ Քիլիսլեան Աղայէկեան',
          arabicName: '',
          cityOfResidence: 'Yerevan, Armenia',
          armenianCityOfResidence: 'Երեւան, Հայաստան',
          arabicCityOfResidence: 'يريفان، أرمينيا',
          age: 61,
          armenianAge: 61,
          arabicAge: 61,
          birthplace: 'Hasaka, Syria',
          armenianBirthplace: 'Հասաքա, Սուրիա',
          arabicBirthplace: ' الحسكة، سوريا',
          ancestralCity: '',
          armenianAncestralCity: '',
          arabicAncestralCity: '',
          route: '',
          armenianRoute: '',
          arabicRoute: '',
          quote: '',
          shortVideoLink: '',
          fullVideoLink: '',
          img: rerooted,
          video: video1,
        },
        {
          name: 'Dikran Chalian',
          armenianName: 'Տիքրան Չալեան',
          arabicName: '',
          cityOfResidence: 'Yerevan, Armenia',
          armenianCityOfResidence: 'Երեւան, Հայաստան',
          arabicCityOfResidence: 'يريفان، أرمينيا',
          age: 64,
          armenianAge: 64,
          arabicAge: 64,
          birthplace: 'Beirut, Lebanon',
          armenianBirthplace: 'Պէյրութ, Լիբանան',
          arabicBirthplace: 'بيروت، لبنان',
          ancestralCity: '',
          armenianAncestralCity: '',
          arabicAncestralCity: '',
          route: '',
          armenianRoute: '',
          arabicRoute: '',
          quote: '',
          shortVideoLink: '',
          fullVideoLink: '',
          img: dikranChalian,
          video: video1,
        },
        {
          name: 'Harout Ghazarian',
          armenianName: 'Յարութ Ղազարեան',
          arabicName: '',
          cityOfResidence: 'Yerevan, Armenia',
          armenianCityOfResidence: 'Երեւան, Հայաստան',
          arabicCityOfResidence: 'يريفان، أرمينيا',
          age: 51,
          armenianAge: 51,
          arabicAge: 51,
          birthplace: 'Aleppo, Syria',
          armenianBirthplace: 'Հալէպ, Սուրիա',
          arabicBirthplace: 'حلب، سوريا',
          ancestralCity: '',
          armenianAncestralCity: '',
          arabicAncestralCity: '',
          route: '',
          armenianRoute: '',
          arabicRoute: '',
          quote: '',
          shortVideoLink: '',
          fullVideoLink: '',
          img: haroutGhazarian,
          video: video1,
        },
        {
          name: 'Sako',
          armenianName: 'Սաքո',
          arabicName: 'ساكو',
          cityOfResidence: 'Yerevan, Armenia',
          armenianCityOfResidence: 'Երեւան, Հայաստան',
          arabicCityOfResidence: 'يريفان، أرمينيا',
          age: 45,
          armenianAge: 45,
          arabicAge: 45,
          birthplace: 'Aleppo, Syria',
          armenianBirthplace: 'Հալէպ, Սուրիա',
          arabicBirthplace: 'حلب، سوريا',
          ancestralCity: '',
          armenianAncestralCity: '',
          arabicAncestralCity: '',
          route: '',
          armenianRoute: '',
          arabicRoute: '',
          quote: '',
          shortVideoLink: '',
          fullVideoLink: '',
          img: sako,
          video: video1,
        },
        {
          name: 'Salpi Minassian',
          armenianName: 'Սալբի Մինասիան',
          arabicName: '',
          cityOfResidence: 'Yerevan, Armenia',
          armenianCityOfResidence: 'Երեւան, Հայաստան',
          arabicCityOfResidence: 'يريفان، أرمينيا',
          age: 70,
          armenianAge: 70,
          arabicAge: 70,
          birthplace: 'Aleppo, Syria',
          armenianBirthplace: 'Հալէպ, Սուրիա',
          arabicBirthplace: 'حلب، سوريا',
          ancestralCity: '',
          armenianAncestralCity: '',
          arabicAncestralCity: '',
          route: '',
          armenianRoute: '',
          arabicRoute: '',
          quote: '',
          shortVideoLink: '',
          fullVideoLink: '',
          img: rerooted,
          video: video1,
        },
        {
          name: 'Hovhannes Keshishian',
          armenianName: 'Հովհաննէս Քէշիշեան',
          arabicName: '',
          cityOfResidence: 'Abovyan, Armenia',
          armenianCityOfResidence: 'Աբովյան, Հայաստան',
          arabicCityOfResidence: 'أبوفيان، أرمينيا',
          age: 64,
          armenianAge: 64,
          arabicAge: 64,
          birthplace: 'Aleppo, Syria',
          armenianBirthplace: 'Հալէպ, Սուրիա',
          arabicBirthplace: 'حلب، سوريا',
          ancestralCity: '',
          armenianAncestralCity: '',
          arabicAncestralCity: '',
          route: '',
          armenianRoute: '',
          arabicRoute: '',
          quote: '',
          shortVideoLink: '',
          fullVideoLink: '',
          img: hovhannesKeshishian,
          video: video1,
        },
        {
          name: 'Hagop George',
          armenianName: 'Հակոբ Ջորջ',
          arabicName: '',
          cityOfResidence: 'Yerevan, Armenia',
          armenianCityOfResidence: 'Երեւան, Հայաստան',
          arabicCityOfResidence: 'يريفان، أرمينيا',
          age: 16,
          armenianAge: 16,
          arabicAge: 16,
          birthplace: 'Aleppo, Syria',
          armenianBirthplace: 'Հալէպ, Սուրիա',
          arabicBirthplace: 'حلب، سوريا',
          ancestralCity: '',
          armenianAncestralCity: '',
          arabicAncestralCity: '',
          route: '',
          armenianRoute: '',
          arabicRoute: '',
          quote: '',
          shortVideoLink: '',
          fullVideoLink: '',
          img: hagopGeorge,
          video: video1,
        },
        {
          name: 'Terez Barsoum',
          armenianName: 'Թերեզ Պարսում',
          arabicName: '',
          cityOfResidence: 'Darpnig, Armenia',
          armenianCityOfResidence: 'Տարփնիկ, Հայաստան',
          arabicCityOfResidence: 'داربنيك، أرمينيا',
          age: 57,
          armenianAge: 57,
          arabicAge: 57,
          birthplace: 'Aleppo, Syria',
          armenianBirthplace: 'Հալէպ, Սուրիա',
          arabicBirthplace: 'حلب، سوريا',
          ancestralCity: '',
          armenianAncestralCity: '',
          arabicAncestralCity: '',
          route: '',
          armenianRoute: '',
          arabicRoute: '',
          quote: '',
          shortVideoLink: '',
          fullVideoLink: '',
          img: terezBarsoum,
          video: video1,
        },
        {
          name: 'Shaghig Minassian',
          armenianName: 'Շաղիկ Մինասեան',
          arabicName: '',
          cityOfResidence: 'Yerevan, Armenia',
          armenianCityOfResidence: 'Երեւան, Հայաստան',
          arabicCityOfResidence: 'يريفان، أرمينيا',
          age: 28,
          armenianAge: 28,
          arabicAge: 28,
          birthplace: 'Aleppo, Syria',
          armenianBirthplace: 'Հալէպ, Սուրիա',
          arabicBirthplace: 'حلب، سوريا',
          ancestralCity: '',
          armenianAncestralCity: '',
          arabicAncestralCity: '',
          route: '',
          armenianRoute: '',
          arabicRoute: '',
          quote: '',
          shortVideoLink: '',
          fullVideoLink: '',
          img: shaghigMinassian,
          video: video1,
        },
        {
          name: 'Garpis Arabatlian',
          armenianName: 'Կարպիս Արապաթլեան',
          arabicName: '',
          cityOfResidence: 'Yerevan, Armenia',
          armenianCityOfResidence: 'Երեւան, Հայաստան',
          arabicCityOfResidence: 'يريفان، أرمينيا',
          age: 55,
          armenianAge: 55,
          arabicAge: 55,
          birthplace: 'Aleppo, Syria',
          armenianBirthplace: 'Հալէպ, Սուրիա',
          arabicBirthplace: 'حلب، سوريا',
          ancestralCity: '',
          armenianAncestralCity: '',
          arabicAncestralCity: '',
          route: '',
          armenianRoute: '',
          arabicRoute: '',
          quote: '',
          shortVideoLink: '',
          fullVideoLink: '',
          img: garpisArabatlian,
          video: video1,
        },
        {
          name: 'Kevork Beyazbegian',
          armenianName: 'Քէորք Պէյազպէկեան',
          arabicName: '',
          cityOfResidence: 'Yerevan, Armenia',
          armenianCityOfResidence: 'Երեւան, Հայաստան',
          arabicCityOfResidence: 'يريفان، أرمينيا',
          age: 53,
          armenianAge: 53,
          arabicAge: 53,
          birthplace: 'Aleppo, Syria',
          armenianBirthplace: 'Հալէպ, Սուրիա',
          arabicBirthplace: 'حلب، سوريا',
          ancestralCity: '',
          armenianAncestralCity: '',
          arabicAncestralCity: '',
          route: '',
          armenianRoute: '',
          arabicRoute: '',
          quote: '',
          shortVideoLink: '',
          fullVideoLink: '',
          img: kevorkBeyazbegian,
          video: video1,
        },
        {
          name: 'Shushanik Narkozian',
          armenianName: 'Շուշանիկ Նարկօզեան',
          arabicName: '',
          cityOfResidence: 'Yerevan, Armenia',
          armenianCityOfResidence: 'Երեւան, Հայաստան',
          arabicCityOfResidence: 'يريفان، أرمينيا',
          age: 53,
          armenianAge: 53,
          arabicAge: 53,
          birthplace: 'Aleppo, Syria',
          armenianBirthplace: 'Հալէպ, Սուրիա',
          arabicBirthplace: 'حلب، سوريا',
          ancestralCity: '',
          armenianAncestralCity: '',
          arabicAncestralCity: '',
          route: '',
          armenianRoute: '',
          arabicRoute: '',
          quote: '',
          shortVideoLink: '',
          fullVideoLink: '',
          img: shushanikNarkozian,
          video: video1,
        },
        {
          name: 'Shant Charoian',
          armenianName: 'Շանթ Չարոյան',
          arabicName: '',
          cityOfResidence: 'Glendale, California',
          armenianCityOfResidence: 'Կլէնտէյլ, Քալիֆորնիա',
          arabicCityOfResidence: 'غلينديل، كاليفورنيا',
          age: 21,
          armenianAge: 21,
          arabicAge: 21,
          birthplace: 'Burbank, California',
          armenianBirthplace: 'Պըրպանք, Քալիֆորնիա',
          arabicBirthplace: 'بربانك، كاليفورنيا',
          ancestralCity: '',
          armenianAncestralCity: '',
          arabicAncestralCity: '',
          route: '',
          armenianRoute: '',
          arabicRoute: '',
          quote: '',
          shortVideoLink: '',
          fullVideoLink: '',
          img: shantCharoian,
          video: video1,
        },
        {
          name: 'Hagop Kazanjian',
          armenianName: 'Հակոբ Գազանճեան',
          arabicName: '',
          cityOfResidence: '--',
          armenianCityOfResidence: '--',
          arabicCityOfResidence: '--',
          age: '--',
          armenianAge: '--',
          arabicAge: '--',
          birthplace: 'Aleppo, Syria',
          armenianBirthplace: 'Հալէպ, Սուրիա',
          arabicBirthplace: 'حلب، سوريا',
          ancestralCity: '',
          armenianAncestralCity: '',
          arabicAncestralCity: '',
          route: '',
          armenianRoute: '',
          arabicRoute: '',
          quote: '',
          shortVideoLink: '',
          fullVideoLink: '',
          img: hagopKazanjian2,
          video: video1,
        },
        {
          name: 'Mayda Chavoushian',
          armenianName: 'Մայտա Չաւուշեան',
          arabicName: '',
          cityOfResidence: 'Yerevan, Armenia',
          armenianCityOfResidence: 'Երեւան, Հայաստան',
          arabicCityOfResidence: 'يريفان، أرمينيا',
          age: 64,
          armenianAge: 64,
          arabicAge: 64,
          birthplace: 'Aleppo, Syria',
          armenianBirthplace: 'Հալէպ, Սուրիա',
          arabicBirthplace: 'حلب، سوريا',
          ancestralCity: '',
          armenianAncestralCity: '',
          arabicAncestralCity: '',
          route: '',
          armenianRoute: '',
          arabicRoute: '',
          quote: '',
          shortVideoLink: '',
          fullVideoLink: '',
          img: maydaChavoushian,
          video: video1,
        },
        {
          name: 'Hagop Kazanjian',
          armenianName: 'Հակոբ Գազանճեան',
          arabicName: '',
          cityOfResidence: 'Yerevan, Armenia',
          armenianCityOfResidence: 'Երեւան, Հայաստան',
          arabicCityOfResidence: 'يريفان، أرمينيا',
          age: 29,
          armenianAge: 29,
          arabicAge: 29,
          birthplace: 'Aleppo, Syria',
          armenianBirthplace: 'Հալէպ, Սուրիա',
          arabicBirthplace: 'حلب، سوريا',
          ancestralCity: '',
          armenianAncestralCity: '',
          arabicAncestralCity: '',
          route: '',
          armenianRoute: '',
          arabicRoute: '',
          quote: '',
          shortVideoLink: '',
          fullVideoLink: '',
          img: hagopKazanjian,
          video: video1,
        },
        {
          name: 'Sarkis Balkhian',
          armenianName: 'Սարքիս Պալխեան',
          arabicName: '',
          cityOfResidence: 'Yerevan, Armenia',
          armenianCityOfResidence: 'Երեւան, Հայաստան',
          arabicCityOfResidence: 'يريفان، أرمينيا',
          age: 30,
          armenianAge: 30,
          arabicAge: 30,
          birthplace: 'Aleppo, Syria',
          armenianBirthplace: 'Հալէպ, Սուրիա',
          arabicBirthplace: 'حلب، سوريا',
          ancestralCity: '',
          armenianAncestralCity: '',
          arabicAncestralCity: '',
          route: '',
          armenianRoute: '',
          arabicRoute: '',
          quote: '',
          shortVideoLink: '',
          fullVideoLink: '',
          img: sarkisBalkhian,
          video: video1,
        },
        {
          name: 'Levon Shant',
          armenianName: 'Լեւոն Շանթ',
          arabicName: '',
          cityOfResidence: 'Yerevan, Armenia',
          armenianCityOfResidence: 'Երեւան, Հայաստան',
          arabicCityOfResidence: 'يريفان، أرمينيا',
          age: 20,
          armenianAge: 20,
          arabicAge: 20,
          birthplace: 'Aleppo, Syria',
          armenianBirthplace: 'Հալէպ, Սուրիա',
          arabicBirthplace: 'حلب، سوريا',
          ancestralCity: '',
          armenianAncestralCity: '',
          arabicAncestralCity: '',
          route: '',
          armenianRoute: '',
          arabicRoute: '',
          quote: '',
          shortVideoLink: '',
          fullVideoLink: '',
          img: levonShant,
          video: video1,
        },
        {
          name: 'Taleen',
          armenianName: 'Թալին',
          arabicName: '',
          cityOfResidence: 'Yerevan, Armenia',
          armenianCityOfResidence: 'Երեւան, Հայաստան',
          arabicCityOfResidence: 'يريفان، أرمينيا',
          age: 40,
          armenianAge: 40,
          arabicAge: 40,
          birthplace: 'Aleppo, Syria',
          armenianBirthplace: 'Հալէպ, Սուրիա',
          arabicBirthplace: 'حلب، سوريا',
          ancestralCity: '',
          armenianAncestralCity: '',
          arabicAncestralCity: '',
          route: '',
          armenianRoute: '',
          arabicRoute: '',
          quote: '',
          shortVideoLink: '',
          fullVideoLink: '',
          img: taleen,
          video: video1,
        },
        {
          name: 'Nareg Dekermenjian',
          armenianName: 'Նարեկ Տեքերմենճեան',
          arabicName: '',
          cityOfResidence: 'Sydney, Australia',
          armenianCityOfResidence: 'Սիտնի, Աւստրալիա ',
          arabicCityOfResidence: 'سيدني، استراليا',
          age: 25,
          armenianAge: 25,
          arabicAge: 25,
          birthplace: 'Aleppo, Syria',
          armenianBirthplace: 'Հալէպ, Սուրիա',
          arabicBirthplace: 'حلب، سوريا',
          ancestralCity: '',
          armenianAncestralCity: '',
          arabicAncestralCity: '',
          route: '',
          armenianRoute: '',
          arabicRoute: '',
          quote: '',
          shortVideoLink: '',
          fullVideoLink: '',
          img: naregDekermenjian,
          video: video1,
        },
      ],
      isOpen: false,
    };

    this.handleClick = this.handleClick.bind(this);
  }

  handleClick = data => {
    this.setState({
      selectedPerson: data,
      isOpen: !this.state.isOpen,
    });
  };

  createTiles = total => {
    const people =
      this.state.selectedPeople === null
        ? this.state.people
        : this.state.selectedPeople;
    const tiles = [];
    for (let i = 0; i < 4; i += 1) {
      if (people[total + i]) {
        tiles.push(
          <Tile
            onClick={() => {
              this.handleClick(people[total + i]);
            }}
          >
            <CircleProfile src={people[total + i].img}>
              {/* <ProfileImage src={img} alt="picture here" /> */}
            </CircleProfile>
            {people[total + i].name}
          </Tile>,
        );
      }
    }
    return (
      <div>
        <TileRow>{tiles}</TileRow>
      </div>
    );
  };

  createRows = () => {
    const people =
      this.state.selectedPeople === null
        ? this.state.people
        : this.state.selectedPeople;
    const rows = [];
    let total = 0;
    while (total < people.length) {
      rows.push(this.createTiles(total));
      total += 4;
    }
    return <div>{rows}</div>;
  };

  searchString = (s, v) => {
    const characters = v.split('');
    const search = s.split('');

    for (let i = 0; i < characters.length; i += 1) {
      if (characters[i] === search[0]) {
        let l = 0;
        let total = 0;
        while (l < search.length) {
          if (
            typeof characters[i + l] === 'string' &&
            characters[i + l] === search[l]
          ) {
            total += 1;
          }
          l += 1;
        }
        if (l === total) {
          return true;
        }
        return false;
      }
    }
    return null; // arrow function asks that something be returned.
  };

  searchProfiles = e => {
    if (e.key === 'Enter') {
      if (e.target.value === '') {
        this.setState({ selectedPeople: this.state.people });
        return null;
      }
      const hits = [];
      console.log('search triggered');
      console.log(e.target.value);
      for (let i = 0; i < this.state.people.length; i += 1) {
        const v = Object.values(this.state.people[i]);
        for (let j = 0; j < v.length; j += 1) {
          if (typeof v[j] === 'string') {
            if (
              this.searchString(
                e.target.value.toLowerCase(),
                v[j].toLowerCase(),
              )
            ) {
              hits.push(this.state.people[i]);
            }
          }
        }
      }
      this.setState({ selectedPeople: hits });
    }
    return null;
  };

  // create row with 4 tiles
  //

  render() {
    return (
      <div>
        <div>
          <Background />
        </div>
        <div>
          <Modal
            show={this.state.isOpen}
            onClose={this.handleClick}
            person={this.state.selectedPerson}
          />
        </div>
        <div>
          <LinkContainer>
            <Link href="/archives" to="/archives">
              Archives
            </Link>
            <Link href="/" to="/">
              Home
            </Link>
            <Link href="/about" to="/about">
              About Us
            </Link>
          </LinkContainer>
          <Header>
            <FormattedMessage {...messages.header} />
          </Header>
          <Search id="searchField" onKeyUp={this.searchProfiles} />
          {this.createRows()}
        </div>
      </div>
    );
  }
}
